### ISSUE TITLE
Blocking version for simple tasks

### ISSUE THREAD

**Issue by halbGefressen** [halcyonnouveau/roux#20]
It's pretty cool that this is async, however sometimes people just want to make a single request and don't want to import 96 dependencies from tokio.

**Comment by beanpuppy** [comment]
I agree, it would be good to give an optional blocking interface also so people won't have to deal with [colouring their functions](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/).

I'm still deciding on how to best do this though. Looking at [reqwest](https://github.com/seanmonstar/reqwest) they seem to just have two copies of the interface, where one has colours and the other doesn't. I don't really like this but I have yet to see something better. Though it probably wouldn't be a huge deal since Roux's interface rarely changes anymore.

If you have any ideas, feel free to spit them out. Otherwise I'll start working on this when I get the time.

**Comment by akarras** [comment]
Stumbled on this crate [maybe_async](https://docs.rs/maybe-async/0.2.2/maybe_async/index.html) and thought it might be of use here. I haven't examined how easy it would be to integrate into roux, but figured I'd drop the link here so I don't forget haha.

I found it on [rspotify](https://github.com/ramsayleung/rspotify)'s README. I like the idea of being able to provide ureq as a swappable backend to further reduce dependencies as well.

**Comment by beanpuppy** [comment]
Nice find @akarras! That definitely looks like it would be useful. Had a quick look at it and rspotify for implementation reference, and it seems like Roux would just need some refactoring with how it deals with the HTTP client to get working.
